USE [master]
GO

/****** Object:  Database [aplicacionBD]    Script Date: 1/6/2024 16:44:14 ******/
CREATE DATABASE [aplicacionBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'aplicacionBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\aplicacionBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'aplicacionBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\aplicacionBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [aplicacionBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [aplicacionBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [aplicacionBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [aplicacionBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [aplicacionBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [aplicacionBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [aplicacionBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [aplicacionBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [aplicacionBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [aplicacionBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [aplicacionBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [aplicacionBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [aplicacionBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [aplicacionBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [aplicacionBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [aplicacionBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [aplicacionBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [aplicacionBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [aplicacionBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [aplicacionBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [aplicacionBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [aplicacionBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [aplicacionBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [aplicacionBD] SET RECOVERY FULL 
GO

ALTER DATABASE [aplicacionBD] SET  MULTI_USER 
GO

ALTER DATABASE [aplicacionBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [aplicacionBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [aplicacionBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [aplicacionBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [aplicacionBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [aplicacionBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [aplicacionBD] SET QUERY_STORE = ON
GO

ALTER DATABASE [aplicacionBD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [aplicacionBD] SET  READ_WRITE 
GO






/****** para crear la tabla  ******/
 
 
USE [aplicacionBD]
GO

/****** Object:  Table [dbo].[Producto]    Script Date: 21/6/2024 16:04:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Producto](
	[pCodigo] [int] NOT NULL,
	[pDetalle] [varchar](255) NULL,
	[pCantidad] [int] NULL,
	[pMarca] [varchar](100) NULL,
	[pPrecio] [numeric](18, 2) NULL,
	[pFecha] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[pCodigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [pDetalle] UNIQUE NONCLUSTERED 
(
	[pDetalle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
