// <auto-generated />
using System;
using GestionStockWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionStockWeb.Migrations
{
    [DbContext(typeof(StockDBContext))]
    partial class StockDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionStockWeb.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("NombreCat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<int?>("CantidadC")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaC")
                        .HasColumnType("date");

                    b.Property<int?>("ProductoFk")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoFkNavigationProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFk")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFkNavigationUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CompraId");

                    b.HasIndex("ProductoFkNavigationProductoId");

                    b.HasIndex("UsuarioFkNavigationUsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int?>("CantidadP")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaFk")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaFkNavigationCategoriaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaFkNavigationCategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("HashU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("GestionStockWeb.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int?>("CantidadV")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaV")
                        .HasColumnType("date");

                    b.Property<int?>("ProductoFk")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoFkNavigationProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFk")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFkNavigationUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("VentaId");

                    b.HasIndex("ProductoFkNavigationProductoId");

                    b.HasIndex("UsuarioFkNavigationUsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Compra", b =>
                {
                    b.HasOne("GestionStockWeb.Models.Producto", "ProductoFkNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("ProductoFkNavigationProductoId");

                    b.HasOne("GestionStockWeb.Models.Usuario", "UsuarioFkNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioFkNavigationUsuarioId");

                    b.Navigation("ProductoFkNavigation");

                    b.Navigation("UsuarioFkNavigation");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Producto", b =>
                {
                    b.HasOne("GestionStockWeb.Models.Categoria", "CategoriaFkNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaFkNavigationCategoriaId");

                    b.Navigation("CategoriaFkNavigation");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Venta", b =>
                {
                    b.HasOne("GestionStockWeb.Models.Producto", "ProductoFkNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("ProductoFkNavigationProductoId");

                    b.HasOne("GestionStockWeb.Models.Usuario", "UsuarioFkNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("UsuarioFkNavigationUsuarioId");

                    b.Navigation("ProductoFkNavigation");

                    b.Navigation("UsuarioFkNavigation");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Producto", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GestionStockWeb.Models.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
